# Generated by Django 4.1.1 on 2022-12-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('is_cash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FinOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_category', models.CharField(max_length=30)),
                ('is_expanses', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('sum', models.FloatField()),
                ('annotation', models.CharField(max_length=200)),
                ('wallet_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin_ops.moneyaccount')),
            ],
        ),
    ]
