# Generated by Django 4.1.1 on 2022-12-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencytype',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='finoperation',
            options={'verbose_name': 'Financial Operation', 'verbose_name_plural': 'Financial Operations'},
        ),
        migrations.AlterModelOptions(
            name='moneyaccount',
            options={'verbose_name': 'Wallet(Account)', 'verbose_name_plural': 'Wallets(Accounts)'},
        ),
    ]
