# Generated by Django 4.1.1 on 2022-12-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_ops', '0003_alter_moneyaccount_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='finoperation',
            old_name='annotation',
            new_name='comment',
        ),
    ]
